--  CREACION DE SYNONIMOS EJECUTARLOS EN CRIS 
CREATE OR REPLACE SYNONYM CLIENTES FOR HOTEL_USER.CLIENTES;
CREATE OR REPLACE SYNONYM HABITACIONES FOR HOTEL_USER.HABITACIONES;
CREATE OR REPLACE SYNONYM RESERVAS FOR HOTEL_USER.RESERVAS;
CREATE OR REPLACE SYNONYM PAGOS FOR HOTEL_USER.PAGOS;

--POSTERIOR A ESO SE DEBEN DE DAR LOS PERMISOS DESDE HOTEL USER PARA CREAR,ELIMINAR Y EDITAR DICHOS SINONIMOS; A SU VEZ SE RECOMIENDA QUE SE USE 
--ESTA LINEA DE CODIGO PARA VERIFICAR QUE LOS SINONIMOS APUNTEN CORRECTAMENTE A LAS TABLAS
SELECT * FROM USER_SYNONYMS; --EJECUTADO DESDE CRIS 