--PERMISOS PARA VER CADA TABLA A CRIS USER 

GRANT SELECT ON CLIENTES TO C##CRIS;
GRANT SELECT ON HABITACIONES TO C##CRIS;
GRANT SELECT ON RESERVAS TO C##CRIS;
GRANT SELECT ON PAGOS TO C##CRIS;

--PERMISOS PARA INSERTAR, ACTUALIZAR Y BORRAR TABLAS 
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTES TO C##Cris; 
GRANT SELECT, INSERT, UPDATE, DELETE ON HABITACIONES TO C##Cris; 
GRANT SELECT, INSERT, UPDATE, DELETE ON PAGOS TO C##Cris; 
GRANT SELECT, INSERT, UPDATE, DELETE ON RESERVAS TO C##Cris; 