---SCRIP PARA VER ROLES
SELECT * FROM USER_ROLE_PRIVS;


--PARA VER PRIVILEGIOS 
SELECT * FROM USER_SYS_PRIVS;


--PRIVILEGIOS SOBRE OBJETOS 
SELECT * FROM USER_TAB_PRIVS;


--VER SI TENGO EL ROL DBA 
SELECT * FROM SESSION_ROLES WHERE ROLE = 'EXP_FULL_DATABASE';
