SELECT USERNAME FROM DBA_USERS; --VERIFICO TODOS LOS USER EXISTENTES 

DROP USER C##RM21062 CASCADE; --ELIMINARION DE USER POR ERRORES 
CREATE USER C##RM21062 IDENTIFIED BY canelo123; --CREACION DE USER 
GRANT CONNECT, RESOURCE TO C##RM21062; --ASIGNACION DE PRIVILEGIOS 
GRANT EXP_FULL_DATABASE TO C##RM21062; 




